// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: film.sql

package db

import (
	"context"
	"time"
)

const createCastMember = `-- name: CreateCastMember :exec
INSERT INTO CastMember(CastMemberId, CastMemberName, CastMemberRole, CastMemberGender)
VALUES($1, $2, $3, $4)
RETURNING CastMemberId, CastMemberName, CastMemberRole, CastMemberGender
`

type CreateCastMemberParams struct {
	Castmemberid     int32  `json:"castmemberid"`
	Castmembername   string `json:"castmembername"`
	Castmemberrole   string `json:"castmemberrole"`
	Castmembergender bool   `json:"castmembergender"`
}

func (q *Queries) CreateCastMember(ctx context.Context, arg CreateCastMemberParams) error {
	_, err := q.db.ExecContext(ctx, createCastMember,
		arg.Castmemberid,
		arg.Castmembername,
		arg.Castmemberrole,
		arg.Castmembergender,
	)
	return err
}

const createFilm = `-- name: CreateFilm :exec
INSERT INTO Film(FilmId,FilmTitle,FilmReleaseDate,FilmDuration) 
VALUES($1,$2,$3,$4)
RETURNING FilmId,FilmTitle,FilmReleaseDate,FilmDuration
`

type CreateFilmParams struct {
	Filmid          int32     `json:"filmid"`
	Filmtitle       string    `json:"filmtitle"`
	Filmreleasedate time.Time `json:"filmreleasedate"`
	Filmduration    int32     `json:"filmduration"`
}

func (q *Queries) CreateFilm(ctx context.Context, arg CreateFilmParams) error {
	_, err := q.db.ExecContext(ctx, createFilm,
		arg.Filmid,
		arg.Filmtitle,
		arg.Filmreleasedate,
		arg.Filmduration,
	)
	return err
}

const createFilmCast = `-- name: CreateFilmCast :exec
INSERT INTO FilmCast(FIlmId, CastMemberId)
VALUES($1, $2)
RETURNING FIlmId, CastMemberId
`

type CreateFilmCastParams struct {
	Filmid       int32 `json:"filmid"`
	Castmemberid int32 `json:"castmemberid"`
}

func (q *Queries) CreateFilmCast(ctx context.Context, arg CreateFilmCastParams) error {
	_, err := q.db.ExecContext(ctx, createFilmCast, arg.Filmid, arg.Castmemberid)
	return err
}

const createFilmGenre = `-- name: CreateFilmGenre :exec
INSERT INTO FilmGenre(Genre_GenreID, Film_FilmId)
VALUES($1, $2)
RETURNING Genre_GenreID, Film_FilmId
`

type CreateFilmGenreParams struct {
	GenreGenreid int32 `json:"genre_genreid"`
	FilmFilmid   int32 `json:"film_filmid"`
}

func (q *Queries) CreateFilmGenre(ctx context.Context, arg CreateFilmGenreParams) error {
	_, err := q.db.ExecContext(ctx, createFilmGenre, arg.GenreGenreid, arg.FilmFilmid)
	return err
}

const createFilmUserStatus = `-- name: CreateFilmUserStatus :exec
INSERT INTO FilmUserStatus(Status_StatusId, Film_FilmId, User_UserID)
VALUES($1, $2, $3)
RETURNING Status_StatusId, Film_FilmId, User_UserID
`

type CreateFilmUserStatusParams struct {
	StatusStatusid int32 `json:"status_statusid"`
	FilmFilmid     int32 `json:"film_filmid"`
	UserUserid     int32 `json:"user_userid"`
}

func (q *Queries) CreateFilmUserStatus(ctx context.Context, arg CreateFilmUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, createFilmUserStatus, arg.StatusStatusid, arg.FilmFilmid, arg.UserUserid)
	return err
}

const createGenre = `-- name: CreateGenre :exec
INSERT INTO Genre(GenreID, GenreName)
VALUES($1, $2)
RETURNING GenreID, GenreName
`

type CreateGenreParams struct {
	Genreid   int32  `json:"genreid"`
	Genrename string `json:"genrename"`
}

func (q *Queries) CreateGenre(ctx context.Context, arg CreateGenreParams) error {
	_, err := q.db.ExecContext(ctx, createGenre, arg.Genreid, arg.Genrename)
	return err
}

const createReview = `-- name: CreateReview :exec
INSERT INTO Review(ReviewStars, ReviewDescription, ReviewUserID, ReviewFilmId)
VALUES($1, $2, $3, $4)
RETURNING ReviewStars, ReviewDescription, ReviewUserID, ReviewFilmId
`

type CreateReviewParams struct {
	Reviewstars       int16  `json:"reviewstars"`
	Reviewdescription string `json:"reviewdescription"`
	Reviewuserid      int32  `json:"reviewuserid"`
	Reviewfilmid      int32  `json:"reviewfilmid"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.ExecContext(ctx, createReview,
		arg.Reviewstars,
		arg.Reviewdescription,
		arg.Reviewuserid,
		arg.Reviewfilmid,
	)
	return err
}

const createStatus = `-- name: CreateStatus :exec
INSERT INTO Status(StatusId, StatusName)
VALUES($1, $2)
RETURNING StatusId, StatusName
`

type CreateStatusParams struct {
	Statusid   int32  `json:"statusid"`
	Statusname string `json:"statusname"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus, arg.Statusid, arg.Statusname)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO "User"(UserID, UserName, UserPasswordHashed, UserBirthday, UserGenre)
VALUES($1, $2, $3, $4, $5)
RETURNING UserID, UserName, UserPasswordHashed, UserBirthday, UserGenre
`

type CreateUserParams struct {
	Userid             int32     `json:"userid"`
	Username           string    `json:"username"`
	Userpasswordhashed string    `json:"userpasswordhashed"`
	Userbirthday       time.Time `json:"userbirthday"`
	Usergenre          bool      `json:"usergenre"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Userid,
		arg.Username,
		arg.Userpasswordhashed,
		arg.Userbirthday,
		arg.Usergenre,
	)
	return err
}

const deleteCastMember = `-- name: DeleteCastMember :exec
DELETE FROM CastMember
WHERE CastMemberId = $1
`

func (q *Queries) DeleteCastMember(ctx context.Context, castmemberid int32) error {
	_, err := q.db.ExecContext(ctx, deleteCastMember, castmemberid)
	return err
}

const deleteFilm = `-- name: DeleteFilm :exec
DELETE FROM Film
WHERE FilmId = $1
`

func (q *Queries) DeleteFilm(ctx context.Context, filmid int32) error {
	_, err := q.db.ExecContext(ctx, deleteFilm, filmid)
	return err
}

const deleteFilmCast = `-- name: DeleteFilmCast :exec
DELETE FROM FilmCast
WHERE FIlmId = $1 AND CastMemberId = $2
`

type DeleteFilmCastParams struct {
	Filmid       int32 `json:"filmid"`
	Castmemberid int32 `json:"castmemberid"`
}

func (q *Queries) DeleteFilmCast(ctx context.Context, arg DeleteFilmCastParams) error {
	_, err := q.db.ExecContext(ctx, deleteFilmCast, arg.Filmid, arg.Castmemberid)
	return err
}

const deleteFilmGenre = `-- name: DeleteFilmGenre :exec
DELETE FROM FilmGenre
WHERE Genre_GenreID = $1 AND Film_FilmId = $2
`

type DeleteFilmGenreParams struct {
	GenreGenreid int32 `json:"genre_genreid"`
	FilmFilmid   int32 `json:"film_filmid"`
}

func (q *Queries) DeleteFilmGenre(ctx context.Context, arg DeleteFilmGenreParams) error {
	_, err := q.db.ExecContext(ctx, deleteFilmGenre, arg.GenreGenreid, arg.FilmFilmid)
	return err
}

const deleteFilmUserStatus = `-- name: DeleteFilmUserStatus :exec
DELETE FROM FilmUserStatus
WHERE Film_FilmId = $1 AND User_UserID = $2
`

type DeleteFilmUserStatusParams struct {
	FilmFilmid int32 `json:"film_filmid"`
	UserUserid int32 `json:"user_userid"`
}

func (q *Queries) DeleteFilmUserStatus(ctx context.Context, arg DeleteFilmUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, deleteFilmUserStatus, arg.FilmFilmid, arg.UserUserid)
	return err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM Genre
WHERE GenreID = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, genreid int32) error {
	_, err := q.db.ExecContext(ctx, deleteGenre, genreid)
	return err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM Review
WHERE ReviewFilmId = $1 AND ReviewUserID = $2
`

type DeleteReviewParams struct {
	Reviewfilmid int32 `json:"reviewfilmid"`
	Reviewuserid int32 `json:"reviewuserid"`
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) error {
	_, err := q.db.ExecContext(ctx, deleteReview, arg.Reviewfilmid, arg.Reviewuserid)
	return err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM Status
WHERE StatusId = $1
`

func (q *Queries) DeleteStatus(ctx context.Context, statusid int32) error {
	_, err := q.db.ExecContext(ctx, deleteStatus, statusid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "User"
WHERE UserID = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userid int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userid)
	return err
}

const getCastMember = `-- name: GetCastMember :one
SELECT CastMemberId, CastMemberName, CastMemberRole, CastMemberGender
FROM CastMember
WHERE CastMemberId = $1
`

func (q *Queries) GetCastMember(ctx context.Context, castmemberid int32) (Castmember, error) {
	row := q.db.QueryRowContext(ctx, getCastMember, castmemberid)
	var i Castmember
	err := row.Scan(
		&i.Castmemberid,
		&i.Castmembername,
		&i.Castmemberrole,
		&i.Castmembergender,
	)
	return i, err
}

const getCastMembers = `-- name: GetCastMembers :many
SELECT CastMemberId, CastMemberName, CastMemberRole, CastMemberGender
FROM CastMember
`

func (q *Queries) GetCastMembers(ctx context.Context) ([]Castmember, error) {
	rows, err := q.db.QueryContext(ctx, getCastMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Castmember
	for rows.Next() {
		var i Castmember
		if err := rows.Scan(
			&i.Castmemberid,
			&i.Castmembername,
			&i.Castmemberrole,
			&i.Castmembergender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilm = `-- name: GetFilm :one
SELECT FilmId,FilmTitle,FilmReleaseDate,FilmDuration
FROM Film
WHERE FilmId = $1
`

func (q *Queries) GetFilm(ctx context.Context, filmid int32) (Film, error) {
	row := q.db.QueryRowContext(ctx, getFilm, filmid)
	var i Film
	err := row.Scan(
		&i.Filmid,
		&i.Filmtitle,
		&i.Filmreleasedate,
		&i.Filmduration,
	)
	return i, err
}

const getFilmCast = `-- name: GetFilmCast :one
SELECT FIlmId, CastMemberId
FROM FilmCast
WHERE FIlmId = $1 AND CastMemberId = $2
`

type GetFilmCastParams struct {
	Filmid       int32 `json:"filmid"`
	Castmemberid int32 `json:"castmemberid"`
}

func (q *Queries) GetFilmCast(ctx context.Context, arg GetFilmCastParams) (Filmcast, error) {
	row := q.db.QueryRowContext(ctx, getFilmCast, arg.Filmid, arg.Castmemberid)
	var i Filmcast
	err := row.Scan(&i.Filmid, &i.Castmemberid)
	return i, err
}

const getFilmCasts = `-- name: GetFilmCasts :many
SELECT FIlmId, CastMemberId
FROM FilmCast
`

func (q *Queries) GetFilmCasts(ctx context.Context) ([]Filmcast, error) {
	rows, err := q.db.QueryContext(ctx, getFilmCasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Filmcast
	for rows.Next() {
		var i Filmcast
		if err := rows.Scan(&i.Filmid, &i.Castmemberid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilmGenre = `-- name: GetFilmGenre :one
SELECT Genre_GenreID, Film_FilmId
FROM FilmGenre
WHERE Genre_GenreID = $1 AND Film_FilmId = $2
`

type GetFilmGenreParams struct {
	GenreGenreid int32 `json:"genre_genreid"`
	FilmFilmid   int32 `json:"film_filmid"`
}

func (q *Queries) GetFilmGenre(ctx context.Context, arg GetFilmGenreParams) (Filmgenre, error) {
	row := q.db.QueryRowContext(ctx, getFilmGenre, arg.GenreGenreid, arg.FilmFilmid)
	var i Filmgenre
	err := row.Scan(&i.GenreGenreid, &i.FilmFilmid)
	return i, err
}

const getFilmGenres = `-- name: GetFilmGenres :many
SELECT Genre_GenreID, Film_FilmId
FROM FilmGenre
`

func (q *Queries) GetFilmGenres(ctx context.Context) ([]Filmgenre, error) {
	rows, err := q.db.QueryContext(ctx, getFilmGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Filmgenre
	for rows.Next() {
		var i Filmgenre
		if err := rows.Scan(&i.GenreGenreid, &i.FilmFilmid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilmUserStatus = `-- name: GetFilmUserStatus :one
SELECT Status_StatusId, Film_FilmId, User_UserID
FROM FilmUserStatus
WHERE Film_FilmId = $1 AND User_UserID = $2
`

type GetFilmUserStatusParams struct {
	FilmFilmid int32 `json:"film_filmid"`
	UserUserid int32 `json:"user_userid"`
}

func (q *Queries) GetFilmUserStatus(ctx context.Context, arg GetFilmUserStatusParams) (Filmuserstatus, error) {
	row := q.db.QueryRowContext(ctx, getFilmUserStatus, arg.FilmFilmid, arg.UserUserid)
	var i Filmuserstatus
	err := row.Scan(&i.StatusStatusid, &i.FilmFilmid, &i.UserUserid)
	return i, err
}

const getFilmUserStatuses = `-- name: GetFilmUserStatuses :many
SELECT Status_StatusId, Film_FilmId, User_UserID
FROM FilmUserStatus
`

func (q *Queries) GetFilmUserStatuses(ctx context.Context) ([]Filmuserstatus, error) {
	rows, err := q.db.QueryContext(ctx, getFilmUserStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Filmuserstatus
	for rows.Next() {
		var i Filmuserstatus
		if err := rows.Scan(&i.StatusStatusid, &i.FilmFilmid, &i.UserUserid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilms = `-- name: GetFilms :many
SELECT FilmId,FilmTitle,FilmReleaseDate,FilmDuration
FROM Film
`

func (q *Queries) GetFilms(ctx context.Context) ([]Film, error) {
	rows, err := q.db.QueryContext(ctx, getFilms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Film
	for rows.Next() {
		var i Film
		if err := rows.Scan(
			&i.Filmid,
			&i.Filmtitle,
			&i.Filmreleasedate,
			&i.Filmduration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenre = `-- name: GetGenre :one
SELECT GenreID, GenreName
FROM Genre
WHERE GenreID = $1
`

type GetGenreRow struct {
	Genreid   int32  `json:"genreid"`
	Genrename string `json:"genrename"`
}

func (q *Queries) GetGenre(ctx context.Context, genreid int32) (GetGenreRow, error) {
	row := q.db.QueryRowContext(ctx, getGenre, genreid)
	var i GetGenreRow
	err := row.Scan(&i.Genreid, &i.Genrename)
	return i, err
}

const getGenres = `-- name: GetGenres :many
SELECT GenreID, GenreName
FROM Genre
`

type GetGenresRow struct {
	Genreid   int32  `json:"genreid"`
	Genrename string `json:"genrename"`
}

func (q *Queries) GetGenres(ctx context.Context) ([]GetGenresRow, error) {
	rows, err := q.db.QueryContext(ctx, getGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGenresRow
	for rows.Next() {
		var i GetGenresRow
		if err := rows.Scan(&i.Genreid, &i.Genrename); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReview = `-- name: GetReview :one
SELECT ReviewStars, ReviewDescription, ReviewUserID, ReviewFilmId
FROM Review
WHERE ReviewFilmId = $1 AND ReviewUserID = $2
`

type GetReviewParams struct {
	Reviewfilmid int32 `json:"reviewfilmid"`
	Reviewuserid int32 `json:"reviewuserid"`
}

func (q *Queries) GetReview(ctx context.Context, arg GetReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReview, arg.Reviewfilmid, arg.Reviewuserid)
	var i Review
	err := row.Scan(
		&i.Reviewstars,
		&i.Reviewdescription,
		&i.Reviewuserid,
		&i.Reviewfilmid,
	)
	return i, err
}

const getReviews = `-- name: GetReviews :many
SELECT ReviewStars, ReviewDescription, ReviewUserID, ReviewFilmId
FROM Review
`

func (q *Queries) GetReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.Reviewstars,
			&i.Reviewdescription,
			&i.Reviewuserid,
			&i.Reviewfilmid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatus = `-- name: GetStatus :one
SELECT StatusId, StatusName
FROM Status
WHERE StatusId = $1
`

func (q *Queries) GetStatus(ctx context.Context, statusid int32) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatus, statusid)
	var i Status
	err := row.Scan(&i.Statusid, &i.Statusname)
	return i, err
}

const getStatuses = `-- name: GetStatuses :many
SELECT StatusId, StatusName
FROM Status
`

func (q *Queries) GetStatuses(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, getStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(&i.Statusid, &i.Statusname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT UserID, UserName, UserPasswordHashed, UserBirthday, UserGenre
FROM "User"
WHERE UserID = $1
`

func (q *Queries) GetUser(ctx context.Context, userid int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Userpasswordhashed,
		&i.Userbirthday,
		&i.Usergenre,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT UserID, UserName, UserPasswordHashed, UserBirthday, UserGenre
FROM "User"
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Userpasswordhashed,
			&i.Userbirthday,
			&i.Usergenre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCastMember = `-- name: UpdateCastMember :exec
UPDATE CastMember
SET CastMemberName = $2, CastMemberRole = $3, CastMemberGender = $4
WHERE CastMemberId = $1
`

type UpdateCastMemberParams struct {
	Castmemberid     int32  `json:"castmemberid"`
	Castmembername   string `json:"castmembername"`
	Castmemberrole   string `json:"castmemberrole"`
	Castmembergender bool   `json:"castmembergender"`
}

func (q *Queries) UpdateCastMember(ctx context.Context, arg UpdateCastMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateCastMember,
		arg.Castmemberid,
		arg.Castmembername,
		arg.Castmemberrole,
		arg.Castmembergender,
	)
	return err
}

const updateFilm = `-- name: UpdateFilm :exec
UPDATE Film
SET FilmTitle = $2 ,FilmReleaseDate = $3, FilmDuration = $4
WHERE FilmId = $1
`

type UpdateFilmParams struct {
	Filmid          int32     `json:"filmid"`
	Filmtitle       string    `json:"filmtitle"`
	Filmreleasedate time.Time `json:"filmreleasedate"`
	Filmduration    int32     `json:"filmduration"`
}

func (q *Queries) UpdateFilm(ctx context.Context, arg UpdateFilmParams) error {
	_, err := q.db.ExecContext(ctx, updateFilm,
		arg.Filmid,
		arg.Filmtitle,
		arg.Filmreleasedate,
		arg.Filmduration,
	)
	return err
}

const updateFilmUserStatus = `-- name: UpdateFilmUserStatus :exec
UPDATE FilmUserStatus
SET Status_StatusId = $3
WHERE Film_FilmId = $1 AND User_UserID = $2
`

type UpdateFilmUserStatusParams struct {
	FilmFilmid     int32 `json:"film_filmid"`
	UserUserid     int32 `json:"user_userid"`
	StatusStatusid int32 `json:"status_statusid"`
}

func (q *Queries) UpdateFilmUserStatus(ctx context.Context, arg UpdateFilmUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFilmUserStatus, arg.FilmFilmid, arg.UserUserid, arg.StatusStatusid)
	return err
}

const updateGenre = `-- name: UpdateGenre :exec
UPDATE Genre
SET GenreName = $2
WHERE GenreID = $1
`

type UpdateGenreParams struct {
	Genreid   int32  `json:"genreid"`
	Genrename string `json:"genrename"`
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) error {
	_, err := q.db.ExecContext(ctx, updateGenre, arg.Genreid, arg.Genrename)
	return err
}

const updateReview = `-- name: UpdateReview :exec
UPDATE Review
SET ReviewStars = $3, ReviewDescription = $4
WHERE ReviewFilmId = $1 AND ReviewUserID = $2
`

type UpdateReviewParams struct {
	Reviewfilmid      int32  `json:"reviewfilmid"`
	Reviewuserid      int32  `json:"reviewuserid"`
	Reviewstars       int16  `json:"reviewstars"`
	Reviewdescription string `json:"reviewdescription"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview,
		arg.Reviewfilmid,
		arg.Reviewuserid,
		arg.Reviewstars,
		arg.Reviewdescription,
	)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE Status
SET StatusName = $2
WHERE StatusId = $1
`

type UpdateStatusParams struct {
	Statusid   int32  `json:"statusid"`
	Statusname string `json:"statusname"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus, arg.Statusid, arg.Statusname)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "User"
SET UserName = $2, UserPasswordHashed = $3, UserBirthday = $4, UserGenre = $5
WHERE UserID = $1
`

type UpdateUserParams struct {
	Userid             int32     `json:"userid"`
	Username           string    `json:"username"`
	Userpasswordhashed string    `json:"userpasswordhashed"`
	Userbirthday       time.Time `json:"userbirthday"`
	Usergenre          bool      `json:"usergenre"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Userid,
		arg.Username,
		arg.Userpasswordhashed,
		arg.Userbirthday,
		arg.Usergenre,
	)
	return err
}
