// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Castmember struct {
	Castmemberid     int32  `json:"castmemberid"`
	Castmembername   string `json:"castmembername"`
	Castmemberrole   string `json:"castmemberrole"`
	Castmembergender string `json:"castmembergender"`
}

type Film struct {
	Filmid          int32     `json:"filmid"`
	Filmtitle       string    `json:"filmtitle"`
	Filmreleasedate time.Time `json:"filmreleasedate"`
	Filmduration    int32     `json:"filmduration"`
}

type Filmcast struct {
	Filmid       int32 `json:"filmid"`
	Castmemberid int32 `json:"castmemberid"`
}

type Filmgenre struct {
	GenreGenreid int32 `json:"genre_genreid"`
	FilmFilmid   int32 `json:"film_filmid"`
}

type Filmuserstatus struct {
	StatusStatusid int32 `json:"status_statusid"`
	FilmFilmid     int32 `json:"film_filmid"`
	UserUserid     int32 `json:"user_userid"`
}

type Genre struct {
	Genrename string `json:"genrename"`
	Genreid   int32  `json:"genreid"`
}

type Review struct {
	Reviewstars       int16  `json:"reviewstars"`
	Reviewdescription string `json:"reviewdescription"`
	Reviewuserid      int32  `json:"reviewuserid"`
	Reviewfilmid      int32  `json:"reviewfilmid"`
}

type Status struct {
	Statusid   int32  `json:"statusid"`
	Statusname string `json:"statusname"`
}

type User struct {
	Userid             int32     `json:"userid"`
	Username           string    `json:"username"`
	Userpasswordhashed string    `json:"userpasswordhashed"`
	Userbirthday       time.Time `json:"userbirthday"`
	Usergenre          string    `json:"usergenre"`
}
